name: Discens Vestigo CI/CD
run-name: Discens Vestigo CI/CD
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26' # Match your project version

      - name: Install Dependencies
        run: |
          go mod download
          go install github.com/a-h/templ/cmd/templ@latest

      - name: Build Assets & Templ
        run: |
          make build

  Test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26' # Match your project version

      - name: Install Dependencies
        run: |
          go mod download
          go install github.com/a-h/templ/cmd/templ@latest

      - name: Run tests and generate coverage
        run: |
          make test

      - name: Generate HTML Report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.html

      - name: Check Coverage Threshold
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
          THRESHOLD=10.0

          echo "Current coverage: $COVERAGE%"

          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
            echo "FAIL: Coverage is below $THRESHOLD%"
            exit 1
          fi
          echo "PASS: Coverage is above $THRESHOLD%" 

  Deploy:
    runs-on: self-hosted

    env:
      DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26' # Match your project version

      - name: Install Dependencies
        run: |
          go mod download
          go install github.com/a-h/templ/cmd/templ@latest

      - name: Build Assets & Templ
        run: |
          make build

      - name: Deploy Binary
        run: |
          # Move binary (ensure runner user has sudoers rights for systemctl/mv)
          sudo mv bin/app ${{ env.DEPLOY_PATH }}
 
      - name: Copy Static Files to Directory
        run: |
          # Sync static assets to the Nginx-served directory
          sudo cp -r static/ ${{ env.DEPLOY_PATH }}

      - name: Fix Permissions and Restart Service
        run: |
          sudo chown -R http:http ${{ env.DEPLOY_PATH }}
          sudo systemctl restart discens-vestigo.service
